version: "3"

volumes:
  bundle:

services:
  exfiles:
    build: .
    image: emaiax/exfiles
    command: bundle exec rspec spec
    volumes:
      - ./:/app/exfiles
      - bundle:/usr/local/bundle
